name: Deploy FastAPI
on:
  push:
    branches: ["feat/deploy"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Docker 빌드 & 이미지 푸시
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/perso-chatbot:latest .

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/perso-chatbot:latest

    # 서버에 배포
    - name: Deploy to Server
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd ~/app
          
          docker stop perso_api || true
          docker rm perso_api || true
          docker pull ${{ secrets.DOCKER_USERNAME }}/perso-chatbot:latest

          # .env 파일 업데이트
          echo "${{ secrets.SETTINGS }}" > .env

          # 새 컨테이너 실행
          docker run -d \
            --name perso_api \
            --env-file .env \
            -p 8000:8000 \
            ${{ secrets.DOCKER_USERNAME }}/perso-chatbot:latest