name: Deploy FastAPI

on:
  push:
    branches: ["feat/deploy"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Docker Login
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build image 
    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/perso-chatbot:latest \
                     -t ${{ secrets.DOCKER_USERNAME }}/perso-chatbot:${{ github.sha }} .

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/perso-chatbot:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/perso-chatbot:${{ github.sha }}

    - name: Deploy to Server
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd ~/app

          docker stop perso_api || true
          docker rm perso_api || true

          docker pull ${{ secrets.DOCKER_USERNAME }}/perso-chatbot:${{ github.sha }}
          echo "${{ secrets.SETTINGS }}" > .env
          
          docker run -d \
            --name perso_api \
            --env-file .env \
            -p 8000:8000 \
            ${{ secrets.DOCKER_USERNAME }}/perso-chatbot:${{ github.sha }}